version: '3.9'

services:
  web:
    build:
      context: ./
      dockerfile: .docker/web.DockerFile
    volumes:
      - ./:/var/www
    ports:
      - '8086:80'
    links:
      - php
  php:
    build:
      context: ./
      dockerfile: .docker/php.DockerFile
    volumes:
      - ./:/var/www
    links:
      - database
      - redis
    environment:
      - 'MYSQL_PORT=3306'
      - 'MYSQL_HOST=database'
      - 'REDIS_PORT=6379'
      - 'REDIS_HOST=redis'
  database:
    platform: linux/x86_64
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3030:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=123123'
      - 'MYSQL_DATABASE=tech'
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
